name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Determine package version
        id: determine-version
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: echo "::set-output name=version::${TAG_NAME#v}"
      - name: Restore dependencies
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
        run: dotnet restore "/p:Version=$VERSION"
      - name: Build
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
        run: dotnet build "/p:Version=$VERSION" --configuration Release --no-restore
      - name: Test
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
        run: dotnet test "/p:Version=$VERSION" --configuration Release --no-build --verbosity normal
      - name: Publish
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push "bin/Release/Ezzatron.Hello.$VERSION.nupkg" --source "github"
