name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  determine-version:
    name: Determine package version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.output-version.outputs.version }}

    steps:
      - name: Output version
        id: output-version
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "::set-output name=version::${TAG_NAME#v}"
          echo "The package version is: ${TAG_NAME#v}"

  publish:
    name: Publish package
    runs-on: ubuntu-latest

    needs:
      - determine-version

    env:
      VERSION: ${{ needs.determine-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore "/p:Version=$VERSION"

      - name: Build
        run: dotnet build "/p:Version=$VERSION" --configuration Release --no-restore

      - name: Test
        run: dotnet test "/p:Version=$VERSION" --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet nuget push "bin/Release/Ezzatron.Hello.$VERSION.nupkg" --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
